eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 9002
spring:
  application:
    name: service-order

# feign设置 开启hystrix
feign:
  hystrix:
    enabled: true

# 设置hystix超时时间 默认一秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
